import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navigation/Navbar";
import Main from "./Main/Main";
import About from "./About/About";
import Contact from "./Contact/Contact";
import Project from "./Project/Project";
import { Analytics } from "@vercel/analytics/next"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar/>
        <Main/>
        <About/>
        {children}
        <Project/>
        <Contact/>
        <Analytics/>
      </body>
    </html>
  );
}
